env:
  node: true
  es2021: true
  browser: true

extends:
  - "airbnb-base"

ignorePatterns: ["dist", "node_modules"]

rules:
  # no-console: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  no-param-reassign: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always